In [3]:
import tensorflow as tf
import numpy as np

In [5]:
pip install tensorflow -U

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
tf

<module 'tensorflow' from 'C:\\Users\\rajesh\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\__init__.py'>

In [8]:
# Create tensors
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

print('Tensor a: ',a)
print('Tensor b: ',b)

Tensor a:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor b:  tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [6]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [27]:
x = tf.constant([[[1,2,3],[7,8,9]],[[0,2,5],[7,6,8]]])
y = tf.constant([[4,5,6],[6,2]])

print('Tensor a: ',x)
print('Tensor b: ',y)

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [28]:
c = tf.add(a,b)

In [16]:
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [17]:
a+b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [23]:
d=a-b
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3])>

In [19]:
a*b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18])>

In [24]:
d.numpy()

array([-3, -3, -3])

In [29]:
a/b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [26]:
a//b   # find division in integer form

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [30]:
b//a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 2])>

In [31]:
b/a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2.5, 2. ])>

In [33]:
# matrix multiplication
# matmul
a_matrix = tf.constant([[1,2],[3,4]])
b_matrix = tf.constant([[5,6],[7,8]])

g = tf.matmul(a_matrix,b_matrix)
print('Matrix Multiplication:',g)

Matrix Multiplication: tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


##### Image Processing / Computer Vision

In [ ]:
# Open CV for real time computer vision an
# Pillow 
# matplotlib to visualise the image
#scikit-image(skimage) for image analysis
